# Generated by Django 5.2 on 2025-05-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pedidoproveedor_detallepedidoproveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedidoproveedor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedidoproveedor',
            options={},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tiempo_entrega_dias',
            field=models.PositiveSmallIntegerField(default=5, help_text='Tiempo estimado de entrega en días'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
