# Generated by Django 5.2 on 2025-04-17 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('preparando', 'Preparando pedido'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('paypal', 'PayPal')], max_length=20)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_envio', models.CharField(max_length=100)),
                ('direccion_envio', models.TextField()),
                ('ciudad_envio', models.CharField(max_length=100)),
                ('estado_envio', models.CharField(max_length=100)),
                ('codigo_postal_envio', models.CharField(max_length=10)),
                ('pais_envio', models.CharField(default='México', max_length=100)),
                ('telefono_envio', models.CharField(max_length=15)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.orden')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Órdenes',
            },
        ),
    ]
